### ISSUE TITLE
Attempt to index global 'Buffer' (a nil value)

### ISSUE THREAD

**Issue by Shatur95** [Akin909/nvim-bufferline.lua#6]
Hi!
I tried your plugin, but have an error:

```
E5108: Error executing lua .../pack/plugins/start/nvim-bufferline.lua/lua/bufferline.lua:499: attempt to index global 'Buffer' (a nil value)
```

I just cloned your plugin to `start` folder (plugins that loaded automatically via built-in Neovim package manager), opened Neovim and executed `lua require'bufferline'.setup()`.
If I put `lua require'bufferline'.setup()` to my configuration It does nothing, so I executed it after startup to see the error.

I using latest Neovim nightly.

**Comment by Akin909** [comment]
@Shatur95 Thanks for trying it out. I think this issue relates to how `packages` work and how lua is loaded using that. I don't use packages myself so I don't really know how it works. Someone else raised a similar issue and it was due to that. I think maybe all the necessary lua files aren't being loaded onto the runtimepath that way. Can you try it with something like `vim-plug` and see if that works

**Comment by Akin909** [comment]
Alternatively I just tweaked the way I'm using `require` for `Buffer` in the plugin on the `dev` branch. Can you try the latest `dev` branch and see if that makes a difference

**Comment by Shatur95** [comment]
Now I have the following error:

```
E5108: Error executing lua ...ack/plugins/start/nvim-bufferline.lua/lua/bufferline.lua:502: attempt to index upvalue 'Buffer' (a nil value)
```

> Can you try it with something like vim-plug and see if that works

Hm... It not works for me even with `vim-plug`, I have exactly the same issue.. I tried the following (this plugin installed via `PlugInstall`, previous installation was removed):

```
call plug#begin(stdpath('data') . '/plugged')
Plug 'Akin909/nvim-bufferline.lua'
call plug#end()
lua require'bufferline'.setup()
```

But all other lua plugins works as expected ([nvim-dap](https://github.com/mfussenegger/nvim-dap), [completion-nvim](https://github.com/mfussenegger/nvim-dap), [diagnostics-nvim](https://github.com/nvim-lua/diagnostic-nvim)) for me.

I using Arch Linux, Neovim with `5f5bd576e5395ef0cd6198f16d10edc1ff4bbe76`.

BTW, could you try native package manager? It's super simple, just move `plugged/nvim-bufferline.lua` (vim-plug folder) to `pack/plugins/start/` (this folder in your `stdpath('config')). Just interesting, is it works for you?

**Comment by Shatur95** [comment]
Hm... I managed to make it work!
After your changes in `dev` branch you need to move all files except `bufferline.lua` to `bufferline/` subfolder. This is how all other lua plugins work.

**Comment by Shatur95** [comment]
But there is another problem. To make it work I need to call `lua require'bufferline'.setup()` twice. First, in my `vimrc` and second - manually after startup (via command). If I call it only manually after startup - neovim will look weird and crash after buffer change. If I call it only in configuration - no effect will happen.

**Comment by Akin909** [comment]
Thanks for investigating @Shatur95, I've had a look at a few lua plugins `nvim-tree` and `nvim-colorizer` and as you say these all nest the way you describe so I've done the same here. I still need to look into how these files are loaded. I think `vim-plug` is handling lua plugins in a different way than the native packages which loads things differently.

I tried tweaking my setup to use packages and read the docs a bit. I think the issue is that using `pack/start` loads the packages *after* your vimrc is loaded
> When Vim starts up, after processing your .vimrc, it scans all directories in
'packpath' for plugins under the "pack/*/start" directory.  First all those
directories are added to 'runtimepath'.

So the first call to `setup` in your `vimrc` will fail with packages using `start` because the plugin won't have been loaded yet. I switched from using `pack/start` to `pack/opt` and calling
```vim
packadd! nvim-bufferline.lua
```

and that works

**Comment by Shatur95** [comment]
I tested, but I still need to call `packadd! nvim-bufferline.lua` twice (in configuration and manualy):

[![asciicast](https://asciinema.org/a/qBpcmpsKPznW92M2NRsrDS95y.svg)](https://asciinema.org/a/qBpcmpsKPznW92M2NRsrDS95y)

**Comment by Shatur95** [comment]
How it looks if I call it only manually once:
[![asciicast](https://asciinema.org/a/2sveX2Ez7bZYRPKkHVFBhwSYm.svg)](https://asciinema.org/a/2sveX2Ez7bZYRPKkHVFBhwSYm)

**Comment by Shatur95** [comment]
> loads the packages after your vimrc is loaded

Yes, it loads all plugins after vimrc. But I can trigger loading manually by `packadd! nvim-bufferline.lua`

**Comment by Akin909** [comment]
@Shatur95 in your example is the plugin still in your `start` directory? since I think that's the only difference between what I tested and what you're seeing. I think calling `packadd` is only applicable to plugins in the `opt` directory according to the snippet from the docs. Can you try the opt directory rather than `start`

Looking at the docs
>  Optional plugins ~
							*pack-add*
> To load an optional plugin from a pack use the `:packadd` command: >
	:packadd foodebug
This searches for "pack/*/opt/foodebug" in 'packpath' and will find
~/.local/share/nvim/site/pack/foo/opt/foodebug/plugin/debugger.vim and source
it.

**Comment by Shatur95** [comment]
> @Shatur95 in your example is the plugin still in your start directory?

No, in all tests I used `opt` directory...

Maybe you have another neovim version? Could you try the latest master?

**Comment by Akin909** [comment]
@Shatur95 I build `nvim` from source. I just pulled master and rebuilt locally just yesterday :thinking:. Can you try to see if this error happens with a minimal vimrc just loading a colorscheme and this plugin. I'll do the same to see if I get the same issues

**Comment by Shatur95** [comment]
Just tied the latest mater myself, the issue still exits.

> Can you try to see if this error happens with a minimal vimrc just loading a colorscheme and this plugin.

Good idea, I had to do this first.

**Comment by Shatur95** [comment]
Wow, it works without plugins. Even on master...
Trying to debug what's happened, maybe someone will find it useful.

**Comment by Akin909** [comment]
I just tried this minimal `init.vim` and it works fine
```vim
packadd! vim-one

set termguicolors
set background=dark
colorscheme one

packadd! nvim-bufferline.lua
lua require'bufferline'.setup{}
```

**Comment by Shatur95** [comment]
I debugged and described two problems, both on my side. Sorry :(

First, it not worked on `master` for me because I have custom script called `buffers.lua` in my lua configuration directory and this just caused namespace collision. In `dev` branch you moved this is fixed collision (so, maybe marge this branch? It looks like this is a good practice).

Second, I need to call it twice because of lightline (that loaded via native packages). What plugin for statusline do you use? If lightline, what is its loading order?

**Comment by Akin909** [comment]
@Shatur95 ah that makes sense that's a pretty good reason to nest the directories to avoid namespace clashes :+1: . I've merged that into master. Re. statusline, I don't use any plugin but I used lightline in the past. I think it tries to set the tabline but you can disable that setting, maybe, I'm not too sure

**Comment by Shatur95** [comment]
It looks like there is no such option, it only allows to use external functions for it. I will consider switching to plain statusline without plugins.

Thanks!
